import { IActionTypes } from '../interfaces/actionInterfaces'

export const TOGGLE_MODE: string = 'TOGGLE_MODE';

export const GET_LIST: IActionTypes = {
  REQUEST: 'GET_LIST_REQUEST',
  SUCCESS: 'GET_LIST_SUCCESS',
  FAILED: 'GET_LIST_FAILED'
}

export const ADD_ITEM: IActionTypes = {
  REQUEST: 'ADD_ITEM_REQUEST',
  SUCCESS: 'ADD_ITEM_SUCCESS',
  FAILED: 'ADD_ITEM_FAILED'
}

export const SELECT_ALL: IActionTypes = {
  REQUEST: 'SELECT_ALL_REQUEST',
  SUCCESS: 'SELECT_ALL_SUCCESS',
  FAILED: 'SELECT_ALL_FAILED'
}

export const TOGGLE_ITEM: IActionTypes = {
  REQUEST: 'TOGGLE_ITEM_REQUEST',
  SUCCESS: 'TOGGLE_ITEM_SUCCESS',
  FAILED: 'TOGGLE_ITEM_FAILED'
}

export const REMOVE_ITEM: IActionTypes = {
  REQUEST: 'REMOVE_ITEM_REQUEST',
  SUCCESS: 'REMOVE_ITEM_SUCCESS',
  FAILED: 'REMOVE_ITEM_FAILED'
}

export const EDIT_ITEM: IActionTypes = {
  REQUEST: 'EDIT_ITEM_REQUEST',
  SUCCESS: 'EDIT_ITEM_SUCCESS',
  FAILED: 'EDIT_ITEM_FAILED'
}

export const REMOVE_ITEMS: IActionTypes = {
  REQUEST: 'REMOVE_ITEMS_REQUEST',
  SUCCESS: 'REMOVE_ITEMS_SUCCESS',
  FAILED: 'REMOVE_ITEMS_FAILED'
}